Auth_User/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('verify/', do_auth, name='verify'),
    path('createUser/', createUser, name='createUser'),
]

Task/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('addTodo/', addTodo, name="addTodo"),
    path('deleteTodo/<int:id>', deleteTodo, name="deleteTodo"),
    # path('test/', test, name="test")
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('auth/', include('Auth_User.urls'), nam),
    path('auth/', include(('Auth_User.urls', 'auth'), namespace='auth')),
    path('task/', include(('Task.urls', 'task'), namespace='task')),
    path('login/', login_view),
    path('register/', register_view),
    path('', home_view),
    path('home/', home_view, name="home"),
    path('logout/', logout_view),
    # path('addTodo/', addTodo, name="addTodo"),
]

Auth_User/models.py
from django.db import models

# Create your models here.

Task/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Task(models.Model):
    status_choices = [
    ('C', 'COMPLETED'),
    ('P', 'PENDING'),
    ]
    title = models.CharField(max_length=50)
    status = models.CharField(max_length=2 , choices=status_choices)
    user  = models.ForeignKey(User  , on_delete= models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

Auth_User/views.py
from django.contrib.auth.models import User
from django.shortcuts import HttpResponse,redirect,render
from django.contrib.auth import authenticate, login,logout

def do_auth(req):
    if req.method == "POST":
        uname = req.POST.get('username')
        print(uname)
        pas = req.POST.get('password')
        user = None
        try:
            user = User.objects.get(username=uname)
        except Exception as e:
            pass
        if user is not None:
            login(req, user)
            return redirect('/home')
        else:
            print("Invalid credentials")
            return redirect('/login')
            pass
    else:
        return HttpResponse("get request to auth")

def createUser(req):
    if req.method == "POST":
        uname = req.POST.get('username')
        print(uname)
        pas = req.POST.get('password')
        user = None
        try:
            user = User.objects.get(username=uname)
        except Exception as e:
            pass
        if user is not None:
            # login(req, user)
            return redirect('/login')
        else:
            user = User.objects.create_user(username=uname,
                                            password=pas)
            login(req, user)
            print("User is new")
            return redirect('/home')
            pass
    else:
        return HttpResponse("get request to auth")

def test(request):
    return HttpResponse("We are in testMode")

Task/views.py
from django.contrib.auth.decorators import login_required
from django.http import request, HttpResponseRedirect
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth import authenticate, login,logout
from django.urls import reverse

from Task.models import Task
# Create your views here.

def addTodo(req):
    print("we are in todo")
    if req.method == 'POST':
        if req.user.is_authenticated:
            title = req.POST.get('title')
            status = req.POST.get('status')
            print(title, status)
            task = Task(title = title, status = status,user = req.user)
            print("user is auth to add")
            task.save()
            return redirect("/home")
            # return HttpResponseRedirect(reverse('home'))
            pass
        else:
            print("in valid cred")
            return redirect("/login")
            pass
        pass
    else:
        return HttpResponse("Get request to todo")

def deleteTodo(req, id):
    Task.objects.get(pk= id).delete()
    return redirect("/home")

todo/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth import authenticate, login,logout

from Task.models import Task

def login_view(request):
    return render(request, "login.html")

def register_view(request):
    return render(request, "register.html")

@login_required()
def home_view(request):
    data = Task.objects.filter(user=request.user)
    context = {'todos':data}
    return render(request, "home.html", context)

def logout_view(req):
    logout(req)
    return redirect('/home')

templates/header.html
  <header style="background-color: #0e387a; font-size: 30px;">
    <div class="container">
      <div class="row justify-content-between py-3">
        <div class="col-md-3">
          <a style="color: #9fafca; font-weight: 800;  text-decoration: none;" >TODO</a>
        </div>
        <div class="col-md-3">
          {% if request.user.is_authenticated %}
          <a class="" style="color: #9fafca;  text-decoration: none;" href="/logout">logout</a>
          {% else %}
          <a class="me-3" style="color: #9fafca; text-decoration: none;" href="/login">login</a>
          <a class="me-3" style="color: #9fafca; text-decoration: none;" href="/register">Sign-up</a>
          {% endif %}
        </div>
      </div>
    </div>
  </header>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>

    {% include 'header.html' %}

    <div class="container mt-5 ">
        <div class="row justify-content-evenly">
            {% comment %} "{% url 'task:addTodo' %}" {% endcomment %}
            <div class="col-md-4 form-group ">
                
                <form action="{% url 'task:addTodo' %}"   method="POST" class="shadow py-4 px-3">
                    {% csrf_token %}
                    <div class="py-3" style="background-color: #a9dce3; font-size: 30px;border-radius: 15px;">
                        <h2 style="color:#7689de; text-align: center;font-weight: 700;">ADD TODO</h2>
                    </div>
                    
                    <label for="title" class="mt-3"><b>Title</b></label>

                    <input type="text" class="form-control mt-1" id="title" aria-describedby="emailHelp" placeholder="Enter Title" name="title" required>
                    
                    <label for="status" class="mt-3"><b>Status</b></label>

                    <select class="form-select mt-1" aria-label="Default select example" name="status" required id="status">
                        <!-- <option >Open this select menu</option> -->
                        <option value="C">COMPLETED</option>
                        <option value="P"  selected>Pending</option>
                    </select>

                    <div class="row mt-3">
                        <div class="col-md-4 justify-content-end">
                            <button class="btn btn-primary px-4 ms-1" type="submit" style="background-color: #8cdce7;color: #7689de; font-weight: 700;">Add</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-md-7 shadow py-4">
                <table class="table table-striped">
                    <thead>
                      <tr>
                        <th scope="col" style="width: 10%;">#</th>
                        <th scope="col" style="width: 35%;">Title</th>
                        <th scope="col" style="width: 35%;">Status</th>
                        <th scope="col" style="width: 10%;"></th>
                        <!-- <th scope="col">Handle</th> -->
                      </tr>
                    </thead>
                    <tbody>
                        {% for todo in todos %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{todo.title}}</td>
                            <td>{{todo.status}}</td>
                            <td><button class="btn btn-danger"><a href="/task/deleteTodo/{{todo.id}}" style="text-decoration: none; color:white;">
                                Remove
                            </a ></button></td>
                          </tr>
                        </tr>  
                        
                        {% endfor %}
                      
                    </tbody>
                  </table>
            </div>
        </div>
    </div>



      <!-- {% if request.user.is_authenticated %}
        <p>User is logged in :)</p>
        <p>Username >  {{ request.user.username }}</p>
        <a href="/logout"> logout </a>
    {% else %}
        <p>User is not logged in :(</p>
    {% endif %} -->




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>

  {% include 'header.html' %}


  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-5 shadow py-4">
        <form action= "{% url 'auth:verify' %}"  method="POST">
          {% csrf_token %}
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="username">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
              </div>
              <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" name="password">
              </div>
      
              <button type="submit" class="btn btn-primary">Login</button>
            </form>
      </div>
    </div>
  </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
 
  {% include 'header.html' %}

  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-5 shadow py-4">
        <form action= "{% url 'auth:createUser' %}"  method="POST">
          {% csrf_token %}
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="username">
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password">
          </div>
  
          <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
  
          <button type="submit" class="btn btn-primary">Register</button>
        </form>
      </div>
    </div>
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>